# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_id', models.IntegerField(choices=[(1, '工作站'), (2, '值班電腦'), (3, '培訓電腦'), (4, '備用電腦'), (5, '汰換機'), (6, '測試機')], default=2)),
                ('latest_data', models.DateField(null=True)),
                ('creare_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '資產表',
            },
        ),
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('assetrecord_type_id', models.IntegerField(choices=[(1, '自動上傳'), (2, 'IT維護'), (3, '故障報修')], default=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('finish_data', models.DateTimeField(null=True)),
                ('asset_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='assetapp.Asset')),
            ],
            options={
                'verbose_name_plural': '資產紀錄表',
            },
        ),
        migrations.CreateModel(
            name='AssetRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '資產變更詳細紀錄表',
            },
        ),
        migrations.CreateModel(
            name='AssetRecordImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': '資產變更詳細紀錄表',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '部門資產表',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=8, verbose_name='插槽位置')),
                ('model', models.CharField(max_length=64, verbose_name='硬盤型號')),
                ('capacity', models.FloatField(verbose_name='硬盤容量')),
            ],
            options={
                'verbose_name_plural': '硬盤表',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('sn', models.CharField(db_index=True, max_length=64, verbose_name='SN')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='製造商')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型號')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('os_platform', models.CharField(blank=True, max_length=16, null=True, verbose_name='系統')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='系統版本')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='邏輯處理器')),
                ('cpu_physical_count', models.IntegerField(blank=True, null=True, verbose_name='處理器內核')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='處理器型號')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assetapp.Asset')),
            ],
            options={
                'verbose_name_plural': '主機表',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32, verbose_name='插槽位置')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='製造商')),
                ('model', models.CharField(max_length=64, verbose_name='型號')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='內存容量')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='內存SN號')),
                ('host_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='assetapp.Host')),
            ],
            options={
                'verbose_name_plural': '内存表',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='網卡名稱')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='型號')),
                ('macaddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC')),
                ('netmask', models.CharField(blank=True, max_length=255, null=True, verbose_name='Netmask')),
                ('host_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='assetapp.Host')),
            ],
            options={
                'verbose_name_plural': '網卡表',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '主機位置表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='暱稱')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='host_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='assetapp.Host'),
        ),
        migrations.AddField(
            model_name='assetrecorddetail',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='assetapp.AssetRecordImage'),
        ),
        migrations.AddField(
            model_name='assetrecorddetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetapp.AssetRecord'),
        ),
        migrations.AddField(
            model_name='assetrecorddetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='assetapp.AssetRecordImage'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetapp.Department', verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='asset',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetapp.Position', verbose_name='主機位置'),
        ),
    ]
