# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctv',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name': 'CCTV'},
        ),
        migrations.AlterModelOptions(
            name='disk',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '硬盤表'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '主機資產表'},
        ),
        migrations.AlterModelOptions(
            name='hostrecord',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '主機紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='ipphone',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name': 'IP電話'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '内存表'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name': '網絡設備'},
        ),
        migrations.AlterModelOptions(
            name='nic',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '網卡表'},
        ),
    ]
