# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20190120_0406'),
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, '自動上傳'), (2, 'IT維護')], default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asset.UserProfile', verbose_name='創建者')),
                ('host_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.Host')),
            ],
            options={
                'verbose_name_plural': '主機紀錄表',
            },
        ),
    ]
