# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Host', to='asset.Asset', verbose_name='資產編號'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type_id',
            field=models.CharField(choices=[('工作站', '工作站'), ('值班電腦', '值班電腦'), ('培訓電腦', '培訓電腦'), ('備用電腦', '備用電腦'), ('汰換機', '汰換機'), ('測試機', '測試機')], default='值班電腦', max_length=64),
        ),
    ]
