# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='發行版本'),
        ),
    ]
