# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20180913_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='sn',
            field=models.CharField(default=999, max_length=255, verbose_name='硬碟序號'),
            preserve_default=False,
        ),
    ]
