# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-11 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20181110_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='設備編號'),
        ),
    ]
