# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_host_os_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='iface_type',
            field=models.CharField(default=1, max_length=64, verbose_name='接口類型'),
            preserve_default=False,
        ),
    ]
