# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20190121_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctv',
            options={'verbose_name': 'CCTV'},
        ),
        migrations.AlterModelOptions(
            name='disk',
            options={'verbose_name_plural': '硬盤表'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'permissions': (('can_view', 'Can view'),), 'verbose_name_plural': '主機資產表'},
        ),
        migrations.AlterModelOptions(
            name='hostrecord',
            options={'verbose_name_plural': '主機紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='ipphone',
            options={'verbose_name': 'IP電話'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': '内存表'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'verbose_name': '網絡設備'},
        ),
        migrations.AlterModelOptions(
            name='nic',
            options={'verbose_name_plural': '網卡表'},
        ),
    ]
