# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20190121_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'permissions': (('can_view_host', 'Can view host'),), 'verbose_name_plural': '主機資產表'},
        ),
    ]
