# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_disk_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='製造商'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='硬盤型號'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='硬碟序號'),
        ),
    ]
