# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190211_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='品牌/型號'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status_date',
            field=models.DateField(blank=True, null=True, verbose_name='使用日期/遺失日期/報廢日期'),
        ),
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='資產名稱'),
        ),
    ]
