# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20190211_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='資產')),
            ],
            options={
                'verbose_name_plural': '資產業務線',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='業務線')),
                ('dent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Department', verbose_name='部門')),
            ],
            options={
                'verbose_name_plural': '業務線',
            },
        ),
        migrations.AlterModelOptions(
            name='assetrepair',
            options={'ordering': ('create_date',), 'verbose_name_plural': '資產維修表'},
        ),
        migrations.AddField(
            model_name='assetbusiness',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name='業務線'),
        ),
    ]
