# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20190213_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbusiness',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name='業務線'),
        ),
    ]
