# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20190213_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='英文簡稱'),
        ),
    ]
