# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-16 09:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_businessunit_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asset.UserProfile', verbose_name='創建者')),
                ('dent', models.ManyToManyField(to='asset.Department', verbose_name='部門')),
            ],
        ),
    ]
