# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-18 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20190218_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetToAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='備註')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assets',
        ),
        migrations.AddField(
            model_name='assettoassets',
            name='asset_objs',
            field=models.ManyToManyField(related_name='_assettoassets_asset_objs_+', to='asset.Asset', verbose_name='關聯資產'),
        ),
        migrations.AddField(
            model_name='assettoassets',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asset.Asset', verbose_name='資產編號'),
        ),
    ]
