# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-18 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20190218_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettoassets',
            name='assets',
        ),
        migrations.AddField(
            model_name='assettoassets',
            name='assets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asset.Asset', verbose_name='關聯資產'),
            preserve_default=False,
        ),
    ]
