# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20181201_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='完成日期')),
                ('asset_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
            ],
            options={
                'verbose_name_plural': '資產紀錄表',
            },
        ),
        migrations.CreateModel(
            name='AssetRepairDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '資產變更詳細紀錄表',
            },
        ),
        migrations.CreateModel(
            name='AssetRepairImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': '資產紀錄圖片表',
            },
        ),
        migrations.RemoveField(
            model_name='assetrecorddetail',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='assetrecorddetail',
            name='record',
        ),
        migrations.RemoveField(
            model_name='assetrecorddetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='assetrecord',
            name='assetrecord_type_id',
        ),
        migrations.RemoveField(
            model_name='assetrecord',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='assetrecord',
            name='photo',
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='type',
            field=models.IntegerField(choices=[(1, '自動上傳'), (2, 'IT維護')], default=0),
        ),
        migrations.AlterField(
            model_name='assetrecord',
            name='asset_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='assetrecord',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.UserProfile', verbose_name='創建者'),
        ),
        migrations.DeleteModel(
            name='AssetRecordDetail',
        ),
        migrations.DeleteModel(
            name='AssetRecordImage',
        ),
        migrations.AddField(
            model_name='assetrepairdetail',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='asset.AssetRepairImage'),
        ),
        migrations.AddField(
            model_name='assetrepairdetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.AssetRecord'),
        ),
        migrations.AddField(
            model_name='assetrepairdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.UserProfile'),
        ),
        migrations.AddField(
            model_name='assetrepair',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='asset.AssetRepairImage'),
        ),
        migrations.AddField(
            model_name='assetrepair',
            name='repairer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetrepair_repairer', to='asset.UserProfile', verbose_name='維修者'),
        ),
    ]
