# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190101_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrepair',
            options={'verbose_name_plural': '資產維修表'},
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='repairer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetrepair', to='asset.UserProfile', verbose_name='維修者'),
        ),
    ]
