# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190101_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrepair',
            name='repairer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairer', to='asset.UserProfile', verbose_name='維修者'),
        ),
    ]
