# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='價格')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
            ],
            options={
                'verbose_name_plural': '資產信息表',
            },
        ),
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('assetrecord_type_id', models.IntegerField(choices=[(1, '自動上傳'), (2, 'IT維護'), (3, '故障報修')], default=2)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='完成日期')),
                ('asset_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='asset.Asset')),
            ],
            options={
                'verbose_name_plural': '資產紀錄表',
            },
        ),
        migrations.CreateModel(
            name='AssetRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '資產變更詳細紀錄表',
            },
        ),
        migrations.CreateModel(
            name='AssetRecordImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': '資產紀錄圖片表',
            },
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('code', models.CharField(max_length=255, verbose_name='代號')),
            ],
            options={
                'verbose_name_plural': '類型',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部門名稱')),
                ('code', models.CharField(max_length=128, verbose_name='部門簡稱')),
                ('block_number', models.CharField(max_length=128, verbose_name='部門工/代號')),
                ('block_number_len', models.PositiveIntegerField(verbose_name='部門工/代號碼長度')),
            ],
            options={
                'verbose_name_plural': '部門',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '位置',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='暱稱')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='員工編號')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('dent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Department', verbose_name='部門')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '用戶',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.UserProfile', verbose_name='部門負責人'),
        ),
        migrations.AddField(
            model_name='assetrecorddetail',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='asset.AssetRecordImage'),
        ),
        migrations.AddField(
            model_name='assetrecorddetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.AssetRecord'),
        ),
        migrations.AddField(
            model_name='assetrecorddetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.UserProfile'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.UserProfile'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='asset.AssetRecordImage'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Catagory', verbose_name='類型'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Department', verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.UserProfile', verbose_name='負責人'),
        ),
    ]
