# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '資產信息表'},
        ),
        migrations.AlterModelOptions(
            name='assetrecord',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '資產紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='assetrepair',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '資產維修表'},
        ),
        migrations.AlterModelOptions(
            name='assetrepairdetail',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '資產維修詳細紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='assetrepairimage',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '資產紀錄圖片表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '類型'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '部門'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '位置'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_add', 'Can add'), ('can_delete', 'Can delete'), ('can_change', 'Can change'), ('can_view', 'Can view')), 'verbose_name_plural': '用戶'},
        ),
    ]
