# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('-purchase_date',), 'permissions': (('can_view_asset', 'Can view asset'),), 'verbose_name_plural': '資產信息表'},
        ),
        migrations.AddField(
            model_name='asset',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
