# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190121_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': (('can_view_asset', 'Can view asset'),), 'verbose_name_plural': '資產信息表'},
        ),
        migrations.AlterModelOptions(
            name='assetrecord',
            options={'verbose_name_plural': '資產紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='assetrepair',
            options={'verbose_name_plural': '資產維修表'},
        ),
        migrations.AlterModelOptions(
            name='assetrepairdetail',
            options={'verbose_name_plural': '資產維修詳細紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='assetrepairimage',
            options={'verbose_name_plural': '資產紀錄圖片表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('can_view category', 'Can view category'),), 'verbose_name_plural': '類型'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('can_view_department', 'Can view department'),), 'verbose_name_plural': '部門'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': (('can_view_location', 'Can view location'),), 'verbose_name_plural': '位置'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_add_userProfile', 'Can add userProfile'),), 'verbose_name_plural': '用戶'},
        ),
    ]
