# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='in_service',
            field=models.IntegerField(choices=[(1, '在職'), (2, '離職'), (3, '停職'), (4, '退休')], default=1, verbose_name='在職狀態'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=64, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性別'),
        ),
    ]
