# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-01 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20181201_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='購買日期'),
        ),
    ]
