# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.IntegerField(default=999, verbose_name='部門代號'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.IntegerField(verbose_name='員工編號'),
        ),
    ]
