# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20190121_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('can_view_category', 'Can view category'),), 'verbose_name_plural': '類型'},
        ),
    ]
