# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20180913_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=128, verbose_name='部門代號'),
        ),
    ]
