# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190212_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbusiness',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='資產'),
        ),
        migrations.AlterField(
            model_name='assetbusiness',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name='業務線'),
        ),
    ]
