# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20181030_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[('未使用', '未使用'), ('使用中', '使用中'), ('遺失', '遺失'), ('報廢', '報廢')], default='RED', max_length=16, verbose_name='狀態'),
        ),
    ]
