# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190121_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_view_userprofile', 'Can view UserProfile'),), 'verbose_name_plural': '用戶'},
        ),
    ]
