# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190103_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrepair',
            name='asset_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='資產編號'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='內文'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='title',
            field=models.CharField(max_length=255, verbose_name='標題'),
        ),
    ]
