# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190212_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbusiness',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name='業務線'),
        ),
    ]
