# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-05 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20181104_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('未使用', '未使用'), ('使用中', '使用中'), ('遺失', '遺失'), ('報廢', '報廢')], default='未使用', max_length=16, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='in_service',
            field=models.CharField(choices=[('在職', '在職'), ('離職', '離職'), ('停職', '停職'), ('退休', '退休')], max_length=16, verbose_name='在職狀態'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=16, verbose_name='性別'),
        ),
    ]
