# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-05 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20181105_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=16, verbose_name='性別'),
        ),
    ]
