# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-17 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='userprofile',
            field=models.ManyToManyField(to='asset.UserProfile', verbose_name='用戶'),
        ),
    ]
