# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_news_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='userprofile',
            field=models.ManyToManyField(blank=True, null=True, to='asset.UserProfile', verbose_name='用戶'),
        ),
    ]
