# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-18 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20190217_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assets',
            field=models.ManyToManyField(blank=True, null=True, to='asset.Asset', verbose_name='關聯資產'),
        ),
        migrations.AddField(
            model_name='asset',
            name='latest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asset.UserProfile', verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asset.UserProfile', verbose_name='負責人'),
        ),
    ]
